### ISSUE TITLE
Please include the tests/ directory in the tarball

### ISSUE THREAD

**Issue by warsaw** [pypa/scripttest#15]
In Debian, we like to run the test suite at package build time, but we can't unless the tests/ directory is included in the tarball released to PyPI.  Please include everything necessary to run the tests in the PyPI tarball.

**Comment by Ivoz** [comment]
Fixed by 0028a3bc42d3d7, @dstufft just needs a release

**Comment by pradyunsg** [comment]
Covered by #20
