### ISSUE TITLE
Using ScriptTest for doctest-like examples

### ISSUE THREAD

**Issue by Anaphory** [pypa/scripttest#17]
I would normally post something like this to a mailing list instead of raising an issue, but the corresponding link in the documentation is dead. (Which I should probably raise separately.)

I am trying to write documentation for a command line tool written in python, and thought that something like `doctest` should be useful for that if it was able to test scripts, like ScriptTest does.

However, it looks like scripttest can only evaluate and match single commands.

Do you think it would be feasable to take 

```
$ command
output
```

examples from documentation and wrap them as calls to a well-defined and widely used shell (`sh` or `bash`) and feed them to `scripttest.TestFileEnvironment.run` and compare the output, to obtain example testing for scripts similar to example testing for functions/properties/classes etc.?

**Comment by Anaphory** [comment]
It's now a thing: [scriptdoctest](github.com/Anaphory/scriptdoctest) – Unfortunately, I had to patch `scripttest.py` in two places, I will feed that back soon.

**Comment by chrahunt** [comment]
Thanks! Let us know if you intend to submit those patches.
